# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-06-03 11:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhood', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neighbourhood',
            name='name',
        ),
    ]
