# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-03 11:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhood', '0002_remove_neighbourhood_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighbourhood',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hoods', to='neighborhood.Profile'),
        ),
        migrations.AlterField(
            model_name='neighbourhood',
            name='neighborhood_name',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
