# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-03 13:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhood', '0003_auto_20190603_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neighbourhood',
            name='admin',
        ),
    ]
