# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-05 14:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhood', '0004_remove_neighbourhood_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='category',
        ),
        migrations.RemoveField(
            model_name='business',
            name='description',
        ),
        migrations.RemoveField(
            model_name='business',
            name='profile',
        ),
    ]
